#undef DEBOUNCE
#define DEBOUNCE 10

#undef TAPPING_TERM
#define TAPPING_TERM 171
#define COMBO_TERM 25
#define ACHORDION_COOLDOWN 200

#define PERMISSIVE_HOLD

#define LEADER_PER_KEY_TIMING
#define LEADER_TIMEOUT 400
// #define IGNORE_MOD_TAP_INTERRUPT
#define HOLD_ON_OTHER_KEY
/* #define HOLD_ON_OTHER_KEY_PRESS_PER_KEY */
#define TAPPING_FORCE_HOLD_PER_KEY
#define ONESHOT_TIMEOUT 1000

#define BOTH_SHIFTS_TURNS_ON_CAPS_WORD

#undef RGB_DISABLE_TIMEOUT
#define RGB_DISABLE_TIMEOUT 900000

#define USB_SUSPEND_WAKEUP_DELAY 0
// still hold layer after double tab, like c$ not cci
#define QUICK_TAP_TERM 0

#undef MOUSEKEY_WHEEL_DELAY
#define MOUSEKEY_WHEEL_DELAY 202

#undef MOUSEKEY_MAX_SPEED
#define MOUSEKEY_MAX_SPEED 14

#undef MOUSEKEY_WHEEL_TIME_TO_MAX
#define MOUSEKEY_WHEEL_TIME_TO_MAX 80

#define FIRMWARE_VERSION u8"3oBGG/gDvAM"
#undef RGB_DISABLE_WHEN_USB_SUSPENDED
#define RGB_MATRIX_STARTUP_SPD 60

#define LEADER_PER_KEY_TIMING
#define LEADER_TIMEOUT 400
// #define IGNORE_MOD_TAP_INTERRUPT
#define HOLD_ON_OTHER_KEY
/* #define HOLD_ON_OTHER_KEY_PRESS_PER_KEY */
#define TAPPING_FORCE_HOLD_PER_KEY
#define ONESHOT_TIMEOUT 1000
