CONSOLE_ENABLE = yes
COMMAND_ENABLE = no
AUDIO_ENABLE = no
DYNAMIC_MACRO_ENABLE = yes
TAP_DANCE_ENABLE = no
# custom
# leader as module now
LEADER_ENABLE = no
COMBO_ENABLE = yes
KEY_OVERRIDE_ENABLE = yes
LAYER_LOCK_ENABLE = yes
DEFERRED_EXEC_ENABLE = yes
CAPS_WORD_ENABLE = yes
REPEAT_KEY_ENABLE = yes
VPATH += keyboards/gboards
KEYCODE_STRING_ENABLE = yes
MOUSE_ENABLE = yes
DEFERRED_EXEC_ENABLE = yes
DYNAMIC_TAPPING_TERM_ENABLE = yes
