enum custom_combo {
    CUSTOM_QU = CHARYBDIS_SAFE_RANGE + 5,
    CUSTOM_AUML,
    CUSTOM_UUML,
    CUSTOM_OUML,
    CUSTOM_BSPACE,
    CUSTOM_REPEAT,
    CUSTOM_END_CAPS,
    CUSTOM_ESC,
    CUSTOM_ENTER,
    CUSTOM_PT_DQUO,
    CUSTOM_LAST
};

enum custom_ext {
    LLOCK = CUSTOM_LAST,
    TURBO
};
